name: paper_chat_ai
description: "A modern desktop application to analyze and chat with research papers using GROBID and Google Gemini."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking & HTTP
  dio: ^5.4.1

  # UI & Markdown / LaTeX Rendering
  flutter_markdown: ^0.7.1
  flutter_math_fork: ^0.7.2
  markdown: ^7.3.0
  google_fonts: ^6.1.0

  # State Management & Persistence
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  # Utility & Window Management
  file_picker: ^13.1.0
  window_manager: ^0.4.3
  pdfrx: ^2.6.5
  xml: ^7.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

